import type * as Icons from 'lucide-react';

/* ------------------------------------------------------------------
   Loan catalogue — the single source of truth for every product page.

   `data.ts` projects this into the summary shape the cards and carousels
   already use, so a product is added in exactly one place and every
   surface picks it up.

   RATES: `rate` is only filled where a published starting rate could be
   verified (see RATES_AS_OF in data.ts). Everything else is null and the
   UI shows "On request" rather than inventing a number.
------------------------------------------------------------------ */

export type Family={id:string;name:string;blurb:string;icon:keyof typeof Icons};

export type Product={
  id:string;
  family:string;
  name:string;
  description:string;          // one-line, used on cards
  icon:keyof typeof Icons;
  tag?:string;
  rate:string|null;            // null => not verified, shown as "On request"
  max:string;                  // indicative ceiling, phrased as a range
  tenure:string;
  what:string;                 // what it is
  suitedTo:string[];           // who it is for
  uses:string[];               // common uses
  eligibility:string[];
  docs:string[];
  fees:[string,string][];
  repayment:string;
  advantages:string[];
  considerations:string[];
  faqs:[string,string][];
};

export const families:Family[]=[
  {id:'personal',   name:'Personal Loans',        blurb:'Unsecured borrowing for planned and unplanned expenses.',              icon:'WalletCards'},
  {id:'business',   name:'Business Loans',        blurb:'Working capital, expansion and equipment finance for businesses.',      icon:'BriefcaseBusiness'},
  {id:'property',   name:'Loan Against Property', blurb:'Borrow against residential, commercial or open land you already own.',  icon:'Building2'},
  {id:'vehicle',    name:'Vehicle Loans',         blurb:'Finance for two-wheelers, cars and commercial vehicles.',               icon:'CarFront'},
  {id:'home',       name:'Home Loans',            blurb:'Purchase, construction, transfer and top-up finance for a home.',       icon:'House'},
  {id:'gold',       name:'Gold Loans',            blurb:'Secured against gold jewellery, usually the fastest to disburse.',      icon:'Gem'},
  {id:'securities', name:'Loan Against Securities',blurb:'Raise money against investments without selling them.',                icon:'LineChart'},
  {id:'education',  name:'Education Loans',       blurb:'Tuition, living costs and travel for study in India or abroad.',        icon:'GraduationCap'},
];

/* shared building blocks — repeated criteria stated once */
const salariedBasics=['Indian resident aged 21–60 at loan maturity','Salaried or self-employed with a steady, documented income','Credit score generally 700+ for the finest pricing','At least one year in the current job or business'];
const kycDocs=['PAN card and Aadhaar','Recent passport-size photograph','Address proof (utility bill, passport or rent agreement)'];
const incomeDocs=['Last 3 months bank statements','Salary slips for 3 months, or 2 years ITR if self-employed'];
const stdFees:[string,string][]=[
  ['Processing fee','Charged by the lender, commonly a percentage of the sanctioned amount. See the offer document for the exact figure.'],
  ['Prepayment / foreclosure','Nil on floating-rate loans to individuals by RBI rule. Fixed-rate products may levy a charge.'],
  ['Late payment','A penal charge applies on any overdue instalment. The rate is set out in your loan agreement.'],
  ['Documentation / stamping','At actuals, where applicable in your state.'],
];
const stdRepay='Repaid in equal monthly instalments (EMIs) by auto-debit from your bank account. The first EMI usually falls due a month after disbursal.';

const commonFaqs:[string,string][]=[
  ['Does checking my eligibility affect my credit score?','No. An eligibility check on this platform is a soft enquiry — invisible to other lenders and with no effect on your score. A hard enquiry happens only when you formally accept an offer and the lender begins underwriting.'],
  ['How long does approval take?','It depends on the product and the lender. Unsecured loans are generally quicker than secured ones, which need the asset to be valued and legally verified. Your chosen lender will confirm timelines.'],
  ['Can I prepay or foreclose early?','Most lenders allow it. Floating-rate loans to individuals carry no foreclosure charge under RBI rules; fixed-rate products may. The exact terms appear on every offer before you accept.'],
];

export const products:Product[]=[

  /* ================= PERSONAL ================= */
  {id:'personal',family:'personal',name:'Personal Loan',icon:'WalletCards',tag:'Popular',
   description:'Flexible funds for life’s important moments.',
   rate:'8.75%',max:'Varies by lender and profile',tenure:'12–84 months',
   what:'A personal loan is unsecured borrowing — no collateral is pledged. The lender decides the amount and rate almost entirely on your income, existing obligations and credit history, and you are free to use the money for any lawful purpose.',
   suitedTo:['Salaried employees with a stable income','Self-employed professionals with filed returns','Borrowers who need funds quickly and have no asset to pledge'],
   uses:['Medical bills not covered by insurance','Home repairs and renovation','Wedding and family events','Consolidating costlier debt','Education fees','Travel'],
   eligibility:salariedBasics,
   docs:[...kycDocs,...incomeDocs],
   fees:stdFees,repayment:stdRepay,
   advantages:['No collateral or guarantor needed in most cases','Money can be used for any lawful purpose','Faster to arrange than a secured loan','Fixed EMI makes budgeting predictable'],
   considerations:['Rates are higher than secured borrowing because the lender has no asset to fall back on','Your advertised rate depends heavily on credit score — thin files pay more','Borrow against what you can comfortably repay, not the maximum offered'],
   faqs:[['Can I use a personal loan for anything?','Broadly yes, for any lawful purpose. Lenders do exclude speculative use such as trading in securities, and some ask what the money is for at application.'],...commonFaqs]},

  {id:'instant-personal',family:'personal',name:'Instant Personal Loan',icon:'Zap',tag:'Fast',
   description:'A digital-first loan for borrowers with a ready credit profile.',
   rate:null,max:'Usually smaller than a standard personal loan',tenure:'3–60 months',
   what:'An instant personal loan is the same product delivered through a fully digital journey. Where your KYC, bank statements and credit record can be verified electronically, a lender can decide in minutes rather than days. Speed comes from automation, not from relaxed criteria.',
   suitedTo:['Borrowers with clean credit history and verifiable digital records','People facing a genuinely time-sensitive expense','Existing customers of a lender who already hold their KYC'],
   uses:['Urgent medical costs','Emergency travel','Short-term cash-flow gaps','Time-bound bills'],
   eligibility:['Salaried, usually with income credited to a bank account','Credit score comfortable enough for automated approval','Aadhaar-linked mobile number for electronic KYC','Bank statements available digitally or via account aggregator'],
   docs:['PAN and Aadhaar for electronic KYC','Digitally fetched or uploaded bank statements','Salary slips, if the lender asks'],
   fees:stdFees,repayment:stdRepay,
   advantages:['Decision and disbursal much faster than a branch process','Minimal paperwork where records verify electronically','Fully online, no branch visit'],
   considerations:['Speed does not mean assured approval — the credit assessment still happens','Smaller ticket sizes and shorter tenures are common','Convenience is sometimes priced in; compare the rate against a standard personal loan'],
   faqs:[['How fast is “instant”?','It varies by lender. Where everything verifies electronically a decision can come in minutes, but disbursal still depends on the lender’s checks and your bank. No lender guarantees a timeline.'],...commonFaqs]},

  {id:'salary-advance',family:'personal',name:'Salary Advance Loan',icon:'CalendarClock',
   description:'A short-term advance repaid against your next pay cycles.',
   rate:null,max:'Typically a multiple of monthly salary',tenure:'1–12 months',
   what:'A salary advance is a small, short-tenure loan sized against your monthly pay. It is designed to bridge a gap before payday rather than fund a large purchase, and it is repaid over a handful of cycles.',
   suitedTo:['Salaried employees with regular salary credits','People needing a small sum for a few weeks or months','Borrowers who would otherwise revolve a credit card balance'],
   uses:['Bridging a gap before payday','Small emergency expenses','Avoiding a costlier card revolve'],
   eligibility:['Salaried with a consistent salary credit history','Minimum monthly income as set by the lender','Employment with an employer the lender recognises'],
   docs:[...kycDocs,'Last 3 months salary slips','Bank statements showing salary credits'],
   fees:stdFees,repayment:'Repaid over a small number of monthly instalments, or in some cases a single repayment on your next salary date. Confirm the structure before you accept.',
   advantages:['Small amounts available without collateral','Short commitment — the debt does not linger','Quick to arrange for existing salary-account holders'],
   considerations:['Cost per rupee borrowed can be high on very short tenures — always check the total, not just the fee','Rolling one advance into the next is a warning sign of a wider cash-flow problem','Not intended for large or long-term needs'],
   faqs:[['Is this the same as an employer salary advance?','No. This is credit from a regulated lender assessed on your profile. An employer advance is an internal arrangement with your company and different rules apply.'],...commonFaqs]},

  {id:'debt-consolidation',family:'personal',name:'Debt Consolidation Loan',icon:'ArrowDownUp',
   description:'Replace several costly debts with one manageable instalment.',
   rate:null,max:'Sized to the debt being cleared',tenure:'12–84 months',
   what:'A consolidation loan is a personal loan taken specifically to repay other borrowings — usually credit card balances and small high-rate loans. You end up with one lender, one EMI and, if the rate is genuinely lower, less interest overall.',
   suitedTo:['Borrowers juggling several EMIs or revolving card balances','People paying card interest, which is typically far higher than a personal loan','Anyone who has missed a payment through sheer administrative confusion'],
   uses:['Clearing revolving credit card balances','Combining multiple small personal loans','Simplifying repayment into a single date'],
   eligibility:[...salariedBasics,'Existing debts should be current — arrears make approval harder'],
   docs:[...kycDocs,...incomeDocs,'Statements for each loan or card being consolidated'],
   fees:stdFees,repayment:stdRepay,
   advantages:['One EMI and one due date instead of several','Can reduce total interest if the new rate is genuinely lower','A single, predictable end date for the debt'],
   considerations:['Consolidation only helps if you stop re-using the cleared cards','A longer tenure can lower the EMI while raising total interest — compare total cost, not the monthly figure','Count the processing fee and any foreclosure charges on the old loans before deciding'],
   faqs:[['Will consolidating improve my credit score?','It can help over time if it means payments are made on time and card utilisation drops. It is not automatic, and closing old accounts can shorten your credit history.'],['How do I know it is worth it?','Add the total remaining interest on your current debts, then compare it with the total interest on the new loan plus its processing fee and any foreclosure charges. Only proceed if the new figure is lower.'],...commonFaqs]},

  {id:'medical-emergency',family:'personal',name:'Medical Emergency Loan',icon:'HeartPulse',
   description:'Funds for treatment costs that insurance does not cover.',
   rate:null,max:'Sized to the treatment estimate',tenure:'6–60 months',
   what:'A personal loan arranged for medical costs. It covers what health insurance does not — deductibles, non-covered procedures, treatment before a claim settles, or care for a family member with no cover of their own.',
   suitedTo:['Families facing hospitalisation costs above their cover','Patients needing treatment excluded from a policy','Anyone bridging the gap while an insurance claim is processed'],
   uses:['Hospital admission and surgery','Treatment excluded from a policy','Post-operative and recovery care','Treatment for an uninsured family member'],
   eligibility:salariedBasics,
   docs:[...kycDocs,...incomeDocs,'Hospital estimate or treatment plan, where the lender asks'],
   fees:stdFees,repayment:stdRepay,
   advantages:['Available without pledging an asset at a difficult time','Can be arranged faster than liquidating investments','Fixed EMI is easier to plan around than an open-ended bill'],
   considerations:['Check whether your insurer offers cashless treatment first — it may remove the need to borrow','Ask the hospital about instalment options before taking on credit','Adequate health insurance is cheaper than borrowing for the same event'],
   faqs:[['Should I borrow or claim on insurance?','Claim first wherever you can. Borrow for the shortfall, or to bridge the period before a claim settles. Your insurer can confirm what is covered.'],...commonFaqs]},

  {id:'travel',family:'personal',name:'Travel Loan',icon:'Plane',
   description:'Spread the cost of a trip over fixed monthly instalments.',
   rate:null,max:'Sized to the trip budget',tenure:'6–48 months',
   what:'A personal loan used for travel — flights, accommodation, visas and tours. The loan is unsecured and the money is disbursed to you, so you book independently rather than through any tie-up.',
   suitedTo:['Travellers who would rather not drain savings for one trip','People with a specific, budgeted itinerary','Families planning a milestone trip'],
   uses:['International holidays','Family pilgrimages','Destination weddings','Milestone celebrations'],
   eligibility:salariedBasics,
   docs:[...kycDocs,...incomeDocs],
   fees:stdFees,repayment:stdRepay,
   advantages:['Spreads a large one-off cost across manageable instalments','Savings stay intact for emergencies','Fixed EMI and a known end date'],
   considerations:['Borrowing for discretionary spending is a genuine choice, not a necessity — be sure the EMI fits','You will be repaying long after the trip ends','Saving in advance for the same trip costs nothing in interest'],
   faqs:[['Is a travel loan different from a personal loan?','In substance, no. It is a personal loan described by its purpose. Compare it against a plain personal loan on rate, fee and total cost.'],...commonFaqs]},

  {id:'wedding',family:'personal',name:'Wedding Loan',icon:'HeartHandshake',
   description:'Finance for wedding costs, repaid over a fixed term.',
   rate:null,max:'Sized to the wedding budget',tenure:'12–60 months',
   what:'A personal loan used for wedding expenses — venue, catering, jewellery, clothing and travel. It is unsecured, and the funds reach your account for you to spend as you choose.',
   suitedTo:['Families managing wedding costs across a short window','Couples funding their own wedding','Anyone who wants to avoid selling long-term assets'],
   uses:['Venue and catering','Jewellery and clothing','Photography and decor','Guest travel and accommodation'],
   eligibility:salariedBasics,
   docs:[...kycDocs,...incomeDocs],
   fees:stdFees,repayment:stdRepay,
   advantages:['Costs spread over a manageable period','Avoids selling investments or gold at short notice','Predictable EMI for household budgeting'],
   considerations:['Wedding budgets expand easily — agree a ceiling before you borrow','A gold loan may cost less if you already own jewellery you can pledge','The repayment continues long after the event'],
   faqs:[['Can two family members apply together?','Some lenders allow a co-applicant, which can improve eligibility since both incomes are considered. Both are then equally liable for repayment.'],...commonFaqs]},

  /* ================= BUSINESS ================= */
  {id:'business',family:'business',name:'Business Loan',icon:'BriefcaseBusiness',
   description:'Working capital to grow your business.',
   rate:'8.15%',max:'Varies with turnover and lender',tenure:'12–84 months',
   what:'A business loan funds the running or growth of an enterprise. Lenders assess the business rather than only the promoter — turnover, bank conduct, GST filings and vintage all matter, alongside the promoter’s own credit record.',
   suitedTo:['Established proprietorships, partnerships and companies','Businesses with filed GST returns and clean banking','Promoters funding a defined growth plan'],
   uses:['Buying stock and raw material','Paying salaries through a lean period','Opening a new location','Marketing and expansion'],
   eligibility:['Business vintage generally 2+ years','Annual turnover above the lender’s threshold','GST returns filed and current','Positive average bank balance over recent months'],
   docs:['GST returns for the last 12 months','12 months current account statements','2 years ITR with computation','Proprietorship, partnership or incorporation proof','KYC for all promoters'],
   fees:stdFees,repayment:stdRepay,
   advantages:['Growth funded without giving up equity','Interest on a business loan is generally a deductible expense','Builds a credit record for the business itself'],
   considerations:['Promoters usually give a personal guarantee, so business debt becomes personal risk','Rates track business risk and are typically above secured retail lending','Cash-flow projections should be realistic, not best-case'],
   faqs:[['Do I need collateral?','Not always. Unsecured business loans exist for businesses with strong banking and filings; secured options usually price lower. Both are worth comparing.'],['Is interest tax deductible?','Interest on borrowing for business purposes is generally allowable as a business expense. Confirm your position with your accountant.'],...commonFaqs]},

  {id:'unsecured-business',family:'business',name:'Unsecured Business Loan',icon:'ShieldCheck',
   description:'Business finance without pledging an asset.',
   rate:null,max:'Generally lower than a secured facility',tenure:'12–60 months',
   what:'An unsecured business loan is assessed on trading performance alone — no property or machinery is pledged. Lenders lean heavily on GST filings, bank statements and the promoter’s credit record, and price for the additional risk they carry.',
   suitedTo:['Service businesses with few physical assets','Businesses unwilling to encumber property','Enterprises needing funds faster than a secured process allows'],
   uses:['Short-term working capital','Bridging receivables','Hiring ahead of a contract','Small equipment purchases'],
   eligibility:['Business vintage as required by the lender','Consistent GST filings and turnover','Healthy average bank balance and no cheque returns','Promoter credit record in good standing'],
   docs:['GST returns','Current account statements','ITR and financial statements','Business registration and KYC'],
   fees:stdFees,repayment:stdRepay,
   advantages:['No asset is encumbered','Faster than a secured facility, which needs valuation and legal checks','Useful where the business owns little property'],
   considerations:['Priced above secured borrowing','Ticket sizes are usually smaller and tenures shorter','A personal guarantee is common, so the debt reaches the promoter'],
   faqs:[['Why is it more expensive than a secured loan?','Because the lender has nothing to recover against if the business cannot repay. That risk is priced into the rate.'],...commonFaqs]},

  {id:'working-capital',family:'business',name:'Working Capital Loan',icon:'Wallet',
   description:'Funds the day-to-day operating cycle, not long-term assets.',
   rate:null,max:'Set as a limit against the operating cycle',tenure:'Renewable, typically annual',
   what:'Working capital finance covers the gap between paying suppliers and collecting from customers. It is often structured as an overdraft or cash credit limit you draw on as needed, paying interest only on the amount actually used.',
   suitedTo:['Businesses with seasonal or lumpy cash flows','Enterprises carrying inventory or receivables','Firms that need flexibility rather than a fixed term loan'],
   uses:['Buying inventory ahead of a season','Paying suppliers before customers pay you','Meeting salary and overhead in a lean month'],
   eligibility:['Established trading history with documented cash flows','GST filings and audited or reviewed financials','Adequate drawing power against stock and receivables'],
   docs:['Audited or provisional financial statements','GST returns and stock statements','Bank statements','Business registration and KYC'],
   fees:[['Processing / renewal fee','Charged at sanction and again at annual renewal. See the sanction letter for the figure.'],['Interest','Charged only on the amount drawn, not the full sanctioned limit.'],['Non-utilisation fee','Some lenders charge a small fee on an unused limit.'],['Stock audit','At actuals, where the lender requires periodic verification.']],
   repayment:'Interest is serviced monthly on the drawn balance. The limit is reviewed and renewed periodically, usually every year, subject to the lender’s assessment.',
   advantages:['Interest is paid only on what you actually draw','Flexible — draw and repay as the cycle demands','Renewable, so it supports an ongoing operating need'],
   considerations:['A limit is not permanent; renewal depends on continued performance','Persistent full utilisation suggests the limit is being used as long-term funding, which it is not designed for','Stock and receivable reporting obligations continue through the year'],
   faqs:[['How is this different from a term loan?','A term loan gives a lump sum repaid on a fixed schedule. Working capital is a revolving limit for the operating cycle, with interest only on what you use.'],...commonFaqs]},

  {id:'msme-sme',family:'business',name:'MSME / SME Loan',icon:'Building2',
   description:'Finance aimed at micro, small and medium enterprises.',
   rate:null,max:'Depends on classification and scheme',tenure:'12–84 months',
   what:'Lending directed at enterprises registered under the MSME framework. Registration can open access to particular schemes and, in some cases, government-backed credit guarantees that improve terms for businesses with limited collateral.',
   suitedTo:['Enterprises with Udyam registration','Manufacturers and service businesses within MSME thresholds','Businesses with limited collateral to offer'],
   uses:['Capacity expansion','Equipment and plant','Working capital','Technology upgrades'],
   eligibility:['Enterprise classified as micro, small or medium under current thresholds','Udyam registration, where the lender or scheme requires it','Filed returns and a demonstrable operating history'],
   docs:['Udyam registration certificate','GST returns and financial statements','Bank statements','Business registration and promoter KYC'],
   fees:stdFees,repayment:stdRepay,
   advantages:['Access to schemes designed for smaller enterprises','Credit guarantee cover can reduce the collateral needed','Terms often more accommodating than general commercial lending'],
   considerations:['Scheme eligibility and terms change — confirm what currently applies','Registration and documentation add steps to the process','Guarantee cover protects the lender, not the borrower, and fees may apply'],
   faqs:[['What is Udyam registration?','It is the government registration that formally classifies an enterprise as micro, small or medium. Several lending schemes require it.'],['Does a credit guarantee mean I cannot default?','No. A guarantee protects the lender against loss. You remain fully liable for repaying the loan.'],...commonFaqs]},

  {id:'startup',family:'business',name:'Startup Loan',icon:'Sparkles',
   description:'Early-stage finance where trading history is limited.',
   rate:null,max:'Usually modest at early stage',tenure:'12–60 months',
   what:'Credit for a business too young to show years of filings. With little trading history, lenders lean on the promoter’s own credit record, the strength of the plan, and any collateral or guarantee available. Terms reflect that uncertainty.',
   suitedTo:['Founders past the idea stage with early revenue','Businesses registered but under the usual vintage threshold','Promoters with a strong personal credit record'],
   uses:['Initial equipment and setup','Early working capital','Hiring a first team','Product development'],
   eligibility:['Business registered and operational','Promoter credit record in good standing','A documented plan with realistic projections','Collateral or a guarantee, depending on the lender'],
   docs:['Business registration and PAN','Business plan and financial projections','Promoter KYC, ITR and bank statements','Any available GST filings'],
   fees:stdFees,repayment:stdRepay,
   advantages:['Funds growth without diluting ownership','Establishes a credit record for a young business','Some schemes specifically target early-stage enterprises'],
   considerations:['Approval is harder without trading history, and terms are tighter','Personal guarantees are near-universal, so founder assets are exposed','Debt requires repayment regardless of how the business performs — equity does not'],
   faqs:[['Can I borrow with no revenue at all?','It is difficult. Most lenders want to see some trading or strong collateral. Grants, incubators and equity may suit a pre-revenue stage better.'],...commonFaqs]},

  {id:'machinery-equipment',family:'business',name:'Machinery / Equipment Loan',icon:'Truck',
   description:'Finance secured against the equipment being purchased.',
   rate:null,max:'A share of the equipment cost',tenure:'12–84 months',
   what:'A loan to buy plant, machinery or equipment, secured against the asset itself. Because the lender holds security, terms are usually better than unsecured business borrowing, and the tenure is matched to the useful life of the asset.',
   suitedTo:['Manufacturers adding or replacing capacity','Service businesses buying specialised equipment','Firms wanting the asset to fund itself over time'],
   uses:['New production machinery','Replacing ageing equipment','Commercial kitchen or medical equipment','IT and infrastructure'],
   eligibility:['Operating business with documented financials','A quotation or proforma invoice for the equipment','Margin contribution from own funds, as set by the lender'],
   docs:['Equipment quotation or proforma invoice','Financial statements and GST returns','Bank statements','Business registration and promoter KYC'],
   fees:stdFees,repayment:stdRepay,
   advantages:['Cheaper than unsecured borrowing because the asset is security','Tenure can be matched to the equipment’s working life','Preserves working capital for operations'],
   considerations:['The equipment is hypothecated to the lender until the loan closes','You fund a margin from your own resources','Equipment can lose value faster than the loan reduces — check the schedule'],
   faqs:[['Do I own the equipment during the loan?','Yes, but it is hypothecated to the lender as security. You cannot sell or dispose of it without their consent while the loan is outstanding.'],...commonFaqs]},
/* ================= LOAN AGAINST PROPERTY ================= */
  {id:'mortgage',family:'property',name:'Loan Against Property',icon:'Building2',
   description:'Unlock liquidity from property you already own.',
   rate:null,max:'A share of the property’s assessed value',tenure:'5–15 years',
   what:'A loan against property (LAP) is secured borrowing against real estate you own — residential, commercial or land. The lender values the property and lends a proportion of that value, known as the loan-to-value or LTV. You keep using the property; the lender holds a charge over it until the loan closes.',
   suitedTo:['Owners of clear-title property needing a large sum','Borrowers who want a longer tenure and lower rate than unsecured lending','Businesses raising funds against a promoter’s property'],
   uses:['Business expansion','Consolidating higher-cost debt','Education or medical costs','Property improvement'],
   eligibility:['Owner of a property with clear, marketable title','Documented income sufficient to service the EMI','Property free of disputes and existing charges, or with them disclosed','Age 21–65 at loan maturity'],
   docs:[...['PAN card and Aadhaar','Address proof'],'Title deed and chain of ownership documents','Approved building plan and occupancy certificate where applicable','Latest property tax receipts','Income proof — salary slips or 2 years ITR','6 months bank statements'],
   fees:[['Processing fee','A percentage of the sanctioned amount, set by the lender.'],['Legal and technical valuation','Charged at actuals for title search and property valuation.'],['Prepayment / foreclosure','Nil on floating-rate loans to individuals for non-business purposes; other cases may attract a charge.'],['Stamp duty on mortgage','As per your state’s schedule.']],
   repayment:stdRepay,
   advantages:['Lower rate than unsecured borrowing because the lender holds security','Larger sums and longer tenures available','You continue to occupy or let the property'],
   considerations:['Your property is at risk if you cannot repay — this is the central trade-off','Processing takes longer because of legal and technical checks','LTV means you cannot borrow the full market value'],
   faqs:[['What is loan-to-value?','LTV is the share of the property’s assessed value a lender will advance. If a property is valued at ₹1 crore and the LTV is 60%, the maximum loan is ₹60 lakh. Lenders set their own LTV caps by property type.'],['Can I sell the property during the loan?','Not freely. The lender holds a charge and must be repaid before the title can transfer cleanly. Discuss any planned sale with them first.'],['What happens if I default?','After due process, the lender can enforce its security and recover the amount by selling the property. This is why LAP should only be taken where repayment is genuinely affordable.'],...commonFaqs]},

  {id:'residential-lap',family:'property',name:'Residential LAP',icon:'House',
   description:'Borrow against a house or flat you own.',
   rate:null,max:'A share of the residential property value',tenure:'5–15 years',
   what:'A loan against property where the security is residential — a self-occupied or let-out house or flat. Residential property is generally the most straightforward security to value, so lenders often apply their most favourable LTV within LAP.',
   suitedTo:['Homeowners with clear title and no outstanding home loan, or a small one','Borrowers needing a large sum at a lower rate than unsecured credit','Families funding education, medical or business needs'],
   uses:['Education costs','Business funding','Debt consolidation','Major medical expenses'],
   eligibility:['Ownership of a residential property with marketable title','Income sufficient to service the EMI alongside existing obligations','Property in a location the lender lends against'],
   docs:['Title deed and ownership chain','Approved plan and occupancy certificate','Property tax receipts','KYC, income proof and bank statements'],
   fees:[['Processing fee','A percentage of the sanctioned amount.'],['Legal and technical','At actuals.'],['Prepayment','Nil on floating-rate loans to individuals for non-business use.'],['Stamp duty','Per state schedule.']],
   repayment:stdRepay,
   advantages:['Typically the best LTV and rate within the LAP family','Long tenure keeps the EMI manageable','You continue living in or letting the property'],
   considerations:['Your home is the security — the consequence of default is losing it','Existing home loan on the property reduces what can be raised','Valuation may come in below your expectation'],
   faqs:[['Can I take LAP on a house that still has a home loan?','Sometimes, as a top-up with the same lender or by refinancing. A second lender taking a fresh charge is harder. Speak to your existing lender first.'],...commonFaqs]},

  {id:'commercial-lap',family:'property',name:'Commercial LAP',icon:'Landmark',
   description:'Raise funds against shop, office or commercial premises.',
   rate:null,max:'A share of the commercial property value',tenure:'5–15 years',
   what:'A loan secured against commercial real estate — a shop, office, warehouse or other business premises. Lenders usually apply a more conservative LTV than for residential property, because commercial assets can be slower to sell.',
   suitedTo:['Business owners who own their premises','Investors holding let commercial property','Enterprises raising working capital against real estate'],
   uses:['Business working capital','Expansion or a second location','Consolidating business debt','Equipment purchase'],
   eligibility:['Ownership of commercial property with clear title','Property in active use or let, in a lender-approved location','Documented business or rental income'],
   docs:['Title and ownership documents','Approved commercial use permissions','Lease or rent agreements, where let','Business financials, GST returns and bank statements'],
   fees:[['Processing fee','A percentage of the sanctioned amount.'],['Legal and technical','At actuals; commercial valuation can cost more than residential.'],['Prepayment','Charges may apply where the loan is for business purposes — confirm in the sanction letter.'],['Stamp duty','Per state schedule.']],
   repayment:stdRepay,
   advantages:['Converts an illiquid asset into working funds without selling it','Rental income from the property can help service the EMI','Longer tenure than most business borrowing'],
   considerations:['LTV is usually lower than on residential property','Foreclosure charges are more likely where the purpose is business','Vacancy in a let property removes the income you were relying on'],
   faqs:[['Is the LTV different from residential LAP?','Generally yes — lenders are more conservative on commercial property because resale can take longer. The exact cap is set by each lender.'],...commonFaqs]},

  {id:'plot-lap',family:'property',name:'Loan Against Plot',icon:'MapPinned',
   description:'Borrow against open land you already own.',
   rate:null,max:'A conservative share of land value',tenure:'5–12 years',
   what:'A loan secured against a plot of land rather than a built property. Because vacant land produces no income and can be harder to sell, lenders apply the most conservative LTV in the LAP family and are selective about location and title.',
   suitedTo:['Owners of clear-title, non-agricultural plots','Borrowers with land in approved layouts','People who want to keep the land rather than sell it'],
   uses:['Construction on the same or another plot','Business funding','Education or family costs','Debt consolidation'],
   eligibility:['Clear, marketable title to the plot','Land within municipal or approved layout limits, typically non-agricultural','Documented income to service the EMI'],
   docs:['Title deed and ownership chain','Layout approval and land-use conversion documents','Encumbrance certificate','Property tax receipts','KYC, income proof and bank statements'],
   fees:[['Processing fee','A percentage of the sanctioned amount.'],['Legal and technical','At actuals; title verification on land is often more involved.'],['Prepayment','As set out in the sanction letter.'],['Stamp duty','Per state schedule.']],
   repayment:stdRepay,
   advantages:['Releases value from land without selling it','Longer tenure and lower rate than unsecured credit','Useful where the land is held for the long term'],
   considerations:['Lowest LTV of the LAP family — expect a conservative valuation','Many lenders decline agricultural land outright','Title issues on land are common and can stop an application'],
   faqs:[['Can I borrow against agricultural land?','Most lenders will not accept it as security for a general-purpose loan. Specific agricultural credit products exist separately.'],...commonFaqs]},

  /* ================= VEHICLE ================= */
  {id:'vehicle',family:'vehicle',name:'Vehicle Loan',icon:'CarFront',
   description:'Drive away with flexible vehicle finance.',
   rate:'7.40%',max:'A share of the on-road price',tenure:'12–84 months',
   what:'A vehicle loan is secured against the vehicle being bought. The lender finances a proportion of the on-road price and you contribute the balance as a down payment. The vehicle is hypothecated to the lender until the loan is repaid.',
   suitedTo:['Buyers who prefer to keep savings intact','Salaried and self-employed applicants with steady income','Anyone comfortable with the vehicle being hypothecated'],
   uses:['Buying a new car','Buying a two-wheeler','Replacing an ageing vehicle','Adding a vehicle for business use'],
   eligibility:['Age 21–65 at loan maturity','Documented, regular income','Credit score in reasonable standing','Valid driving licence, where the lender asks'],
   docs:[...['PAN card and Aadhaar','Address proof'],'Income proof — salary slips or ITR','Bank statements','Proforma invoice or quotation for the vehicle','Driving licence'],
   fees:[['Processing fee','A percentage of the loan or a flat amount, set by the lender.'],['Hypothecation charges','Payable to the RTO for endorsing the lender’s interest.'],['Prepayment / foreclosure','Terms vary — check the sanction letter.'],['Late payment','A penal charge on overdue instalments.']],
   repayment:stdRepay,
   advantages:['Secured against the vehicle, so rates are lower than unsecured borrowing','Savings remain available for other needs','Fixed EMI over a known term'],
   considerations:['A vehicle depreciates while the loan runs — you can owe more than it is worth','Insurance is compulsory throughout the loan and adds to running cost','Down payment, registration and insurance are payable upfront'],
   faqs:[['What is hypothecation?','It records the lender’s interest in the vehicle on its registration certificate. Once the loan is repaid you obtain a no-objection certificate and have the entry removed.'],['How much down payment is needed?','Lenders finance a proportion of the on-road price and you pay the rest. The exact share varies by lender, vehicle and your profile.'],...commonFaqs]},

  {id:'two-wheeler',family:'vehicle',name:'Two Wheeler Loan',icon:'Bike',
   description:'Finance for a motorcycle or scooter.',
   rate:null,max:'A share of the on-road price',tenure:'12–48 months',
   what:'A loan secured against a motorcycle or scooter. Ticket sizes are small and tenures short, so approval is often quicker than for larger vehicle finance, though the same hypothecation and insurance rules apply.',
   suitedTo:['First-time borrowers building a credit record','Daily commuters','Buyers wanting a small, short commitment'],
   uses:['Commuting to work','Replacing an older two-wheeler','Delivery or gig work'],
   eligibility:['Age 21–65 at loan maturity','Documented income, salaried or self-employed','Valid driving licence'],
   docs:['PAN and Aadhaar','Address proof','Income proof and bank statements','Driving licence','Vehicle quotation'],
   fees:[['Processing fee','Flat or percentage, set by the lender.'],['Hypothecation charges','Payable to the RTO.'],['Prepayment','Terms vary by lender.'],['Late payment','Penal charge on overdue instalments.']],
   repayment:stdRepay,
   advantages:['Small ticket, short tenure, quick to arrange','A clean repayment record helps build credit history','Down payment requirement is modest'],
   considerations:['Cost per rupee borrowed can be high on small, short loans','Two-wheelers depreciate quickly','Insurance must be maintained for the life of the loan'],
   faqs:[['Can I get one with no credit history?','It is one of the more accessible secured products for a first-time borrower, but approval still depends on income and the lender’s policy.'],...commonFaqs]},

  {id:'new-car',family:'vehicle',name:'New Car Loan',icon:'Car',
   description:'Finance for a brand-new car.',
   rate:'7.40%',max:'A share of the on-road price',tenure:'12–84 months',
   what:'A loan to buy a new car, secured against the vehicle. New cars attract the best rates in vehicle finance because the security is fresh, valuation is straightforward and resale value is predictable.',
   suitedTo:['Buyers purchasing from an authorised dealer','Applicants with steady documented income','People who want the longest tenure available in vehicle finance'],
   uses:['First car purchase','Upgrading the family car','Adding a second vehicle'],
   eligibility:['Age 21–65 at loan maturity','Regular documented income','Credit score in good standing','Valid driving licence'],
   docs:['PAN and Aadhaar','Address proof','Salary slips or ITR','Bank statements','Proforma invoice from the dealer'],
   fees:[['Processing fee','Set by the lender, often negotiable at the dealership.'],['Hypothecation charges','Payable to the RTO.'],['Prepayment','Terms vary; some lenders restrict prepayment in the first year.'],['Late payment','Penal charge on overdue instalments.']],
   repayment:stdRepay,
   advantages:['Typically the best-priced option within vehicle finance','Longer tenures available than on used cars','Dealer and lender offers can sometimes be combined'],
   considerations:['A new car loses value fastest in its first years','On-road price includes registration and insurance, which the loan may not fully cover','Compare the dealer’s finance against an independent lender before signing'],
   faqs:[['Should I take dealer finance or arrange my own?','Compare both. Dealer arrangements are convenient and sometimes subsidised, but an independent lender may price better. Compare total cost, not the EMI alone.'],...commonFaqs]},

  {id:'used-car',family:'vehicle',name:'Used Car Loan',icon:'Car',
   description:'A smarter way to finance your next car.',
   rate:null,max:'A share of the valued price',tenure:'12–72 months',
   what:'A loan to buy a pre-owned car. The lender values the vehicle, and its age and condition drive both the amount advanced and the tenure allowed. Rates sit above new-car finance because used vehicles are harder to value and resell.',
   suitedTo:['Buyers seeking better value than a new car','People buying from a dealer or certified pre-owned programme','Second-car buyers'],
   uses:['Buying a first car affordably','Adding a second family vehicle','Replacing an older car'],
   eligibility:['Age 21–65 at loan maturity','Documented income','Vehicle within the lender’s age limit, commonly up to 8–10 years at loan maturity','Clear ownership record for the vehicle'],
   docs:['PAN and Aadhaar','Address proof','Income proof and bank statements','Registration certificate and insurance of the vehicle','Valuation report, where required','Sale agreement with the seller'],
   fees:[['Processing fee','Set by the lender.'],['Valuation charge','For inspecting and valuing the vehicle.'],['Transfer and hypothecation','RTO charges for ownership transfer and endorsing the lender.'],['Prepayment','Terms vary by lender.']],
   repayment:stdRepay,
   advantages:['A given budget buys more car than new','Steepest depreciation has already been absorbed by the first owner','Shorter tenures mean less total interest'],
   considerations:['Rates are higher and tenures shorter than new-car finance','Condition and service history matter — get an independent inspection','Private-party sales are harder to finance than dealer purchases'],
   faqs:[['How old a car can I finance?','Lenders set an age cap, commonly requiring the car to be under about 8–10 years old when the loan matures. The exact limit varies.'],['Can I finance a car bought from an individual?','Some lenders allow it with proper documentation and valuation, though dealer purchases are generally simpler to fund.'],...commonFaqs]},

  {id:'commercial',family:'vehicle',name:'Commercial Vehicle Loan',icon:'Truck',
   description:'Finance for vehicles used to earn a living.',
   rate:null,max:'A share of the vehicle cost',tenure:'12–60 months',
   what:'Finance for vehicles used commercially — goods carriers, passenger vehicles, tippers and similar. Lenders assess the earning potential of the vehicle and the operator’s experience alongside the usual credit checks.',
   suitedTo:['Transport operators and fleet owners','First-time commercial vehicle buyers with experience in the trade','Businesses adding delivery capacity'],
   uses:['Buying a goods carrier','Adding to a fleet','Replacing an ageing commercial vehicle','Passenger transport operations'],
   eligibility:['Experience in the transport trade, as required by the lender','Documented business or contract income','Valid commercial driving licence and permits','Credit record in reasonable standing'],
   docs:['KYC and address proof','Business registration, where applicable','ITR and bank statements','Existing vehicle registration and permits','Quotation for the vehicle','Contracts or freight agreements, if available'],
   fees:[['Processing fee','Set by the lender.'],['Hypothecation and permit charges','Payable to the RTO and transport authority.'],['Prepayment','Terms vary; commercial loans more often carry a charge.'],['Late payment','Penal charge on overdue instalments.']],
   repayment:'Repaid in monthly instalments. Some lenders structure repayment around the earning cycle of the vehicle — discuss this before you accept.',
   advantages:['The vehicle can generate the income that services the loan','Longer tenures available than unsecured business credit','Builds an asset base for a transport business'],
   considerations:['Income depends on utilisation — idle vehicles still incur EMIs','Permits, insurance, maintenance and fuel are substantial running costs','Commercial vehicles depreciate with use as well as age'],
   faqs:[['Is a contract or freight agreement required?','Not always, but showing committed work strengthens an application considerably, particularly for a first vehicle.'],...commonFaqs]},

  {id:'heavy-commercial',family:'vehicle',name:'Heavy Commercial Vehicle Loan',icon:'Truck',
   description:'Finance for trucks, tippers and heavy fleet vehicles.',
   rate:null,max:'A share of the vehicle cost',tenure:'12–60 months',
   what:'Finance for heavy goods vehicles and construction-linked transport. Ticket sizes are large, so lenders look closely at operating experience, existing fleet performance and the contracts the vehicle will service.',
   suitedTo:['Established fleet operators','Contractors with committed haulage work','Operators replacing ageing heavy vehicles'],
   uses:['Adding trucks or tippers to a fleet','Construction and mining haulage','Long-haul freight operations'],
   eligibility:['Demonstrable experience operating heavy vehicles','Existing fleet and contract record, where applicable','Documented business income','Valid permits and licences'],
   docs:['Business registration and KYC','ITR, financial statements and bank statements','Existing fleet registration documents','Contracts or work orders','Vehicle quotation'],
   fees:[['Processing fee','Set by the lender.'],['Hypothecation, permit and fitness charges','Payable to the relevant authorities.'],['Prepayment','Terms vary by lender.'],['Late payment','Penal charge on overdue instalments.']],
   repayment:'Monthly instalments, sometimes structured around the operating cycle. Confirm the schedule in the sanction letter.',
   advantages:['Finances a revenue-generating asset','Tenure matched to the vehicle’s working life','Supports fleet growth without exhausting working capital'],
   considerations:['Large exposure — a single idle vehicle strains cash flow','Running costs are significant and often underestimated','Regulatory and permit requirements are more demanding than for light vehicles'],
   faqs:[['Do I need existing fleet experience?','Most lenders prefer it for heavy vehicles, given the exposure. First-time operators may need stronger collateral or a guarantee.'],...commonFaqs]},

  /* ================= HOME ================= */
  {id:'home',family:'home',name:'Home Loan',icon:'House',tag:'Popular',
   description:'Make your dream home a confident decision.',
   rate:'7.10%',max:'A share of the property value',tenure:'5–30 years',
   what:'A home loan finances the purchase or construction of a residence, secured by a mortgage over that property. It is the longest financial commitment most households take on, which makes the total interest paid across the tenure far more important than the headline rate.',
   suitedTo:['First-time buyers with steady documented income','Families upgrading to a larger home','Buyers who want the longest available tenure to keep EMIs manageable'],
   uses:['Buying a ready or under-construction home','Constructing on land you own','Extending or renovating an existing home'],
   eligibility:['Age 21–65 at loan maturity','Stable income for at least two years','Property with clear, marketable title','Credit score generally 725+ for the finest pricing'],
   docs:['PAN, Aadhaar and address proof','6 months bank statements','Form 16 and 2 years ITR','Sale agreement, title deed and approved building plan','Property tax receipts and occupancy certificate where applicable'],
   fees:[['Processing fee','A percentage of the sanctioned amount; frequently waived or reduced on offers.'],['Legal and technical valuation','Charged at actuals for title search and property inspection.'],['Prepayment / foreclosure','Nil for individual borrowers on floating-rate home loans, by RBI rule.'],['Stamp duty on mortgage','As per your state’s schedule.']],
   repayment:'Repaid in monthly instalments over the agreed tenure. On an under-construction property you may pay only interest on the amount disbursed until construction completes, after which full EMIs begin.',
   advantages:['Among the lowest interest rates available to individuals','Tax deductions may apply on both interest and principal','No foreclosure charge on floating-rate loans to individuals','Long tenure keeps monthly outgo manageable'],
   considerations:['The property is mortgaged for the life of the loan','A floating rate can rise — a small change over 20 years is a large sum','Registration, stamp duty and fees are payable upfront and are substantial','Total interest over a long tenure can approach the principal itself'],
   faqs:[['How much deposit will I need?','Lenders finance a proportion of the property value and you fund the rest, plus stamp duty and registration. The exact share depends on the lender and the property value.'],['Should I choose a shorter tenure?','A shorter tenure means a higher EMI but substantially less total interest. Use the EMI calculator to compare total payable, not just the monthly figure.'],['Is a joint application better?','Adding a co-applicant with income can improve eligibility, and both may be able to claim tax deductions on their share. Both become equally liable for repayment.'],...commonFaqs]},

  {id:'home-purchase',family:'home',name:'Home Purchase Loan',icon:'House',
   description:'Finance for buying a ready or under-construction home.',
   rate:null,max:'A share of the property value',tenure:'5–30 years',
   what:'The standard home loan used to buy a residential property, whether ready to move in or still under construction. The lender disburses to the seller or builder against the sale agreement and its own legal and technical clearance.',
   suitedTo:['Buyers with an identified property and signed agreement','First-time home buyers','Families relocating or upgrading'],
   uses:['Buying a flat or house from a builder','Buying a resale property','Purchasing in an approved project'],
   eligibility:['Age 21–65 at loan maturity','Two years of stable documented income','Property with clear title in a location the lender approves','Own contribution ready for the margin, stamp duty and registration'],
   docs:['KYC and address proof','Income proof — Form 16, salary slips or 2 years ITR','6 months bank statements','Sale agreement and allotment letter','Title documents and approved plan'],
   fees:[['Processing fee','A percentage of the sanctioned amount.'],['Legal and technical','At actuals.'],['Prepayment','Nil on floating-rate loans to individuals.'],['Stamp duty','Per state schedule.']],
   repayment:'Monthly instalments over the tenure. Under-construction purchases are disbursed in stages, with interest payable on the drawn amount until completion.',
   advantages:['Lowest rates available to individual borrowers','Long tenure spreads the cost','Tax deductions may apply — see the tax section'],
   considerations:['Under-construction purchases carry completion and delay risk','Verify the project’s regulatory registration and approvals independently','Budget for stamp duty, registration and interiors on top of the price'],
   faqs:[['What is a pre-approved property?','A project a lender has already legally and technically vetted, which can shorten processing. It is not an endorsement of the builder — do your own checks.'],...commonFaqs]},

  {id:'home-construction',family:'home',name:'Home Construction Loan',icon:'Building2',
   description:'Finance for building a house on land you own.',
   rate:null,max:'A share of the construction estimate',tenure:'5–30 years',
   what:'A loan to construct a house on a plot you already own. Money is released in stages tied to construction milestones, rather than as a single lump sum, and the lender inspects progress before each release.',
   suitedTo:['Owners of clear-title plots ready to build','Families building to their own design','Borrowers with an approved plan and cost estimate'],
   uses:['Building a new house','Completing partially built construction','Adding a floor to an existing home'],
   eligibility:['Ownership of the plot with clear title','Approved building plan from the local authority','Documented income to service the EMI','Construction estimate from an approved engineer or architect'],
   docs:['Plot title deed and ownership chain','Approved building plan and construction permission','Detailed cost estimate','KYC, income proof and bank statements'],
   fees:[['Processing fee','A percentage of the sanctioned amount.'],['Legal and technical','At actuals, including periodic progress inspections.'],['Prepayment','Nil on floating-rate loans to individuals.'],['Stamp duty','Per state schedule.']],
   repayment:'Interest is payable on the amount disbursed during construction. Full EMIs generally begin once construction is complete and the final tranche is released.',
   advantages:['Build to your own specification','Money released in step with actual spending','Same favourable rate treatment as other home loans'],
   considerations:['Disbursal depends on the lender verifying construction progress','Cost overruns are common — keep a contingency outside the loan','Delays extend the interest-only period and the total cost'],
   faqs:[['How is the money released?','In tranches tied to construction milestones — foundation, slab, roofing and so on — with the lender inspecting before each release.'],...commonFaqs]},

  {id:'home-balance-transfer',family:'home',name:'Home Loan Balance Transfer',icon:'ArrowDownUp',
   description:'Move an existing home loan to a lender charging less.',
   rate:null,max:'The outstanding balance being transferred',tenure:'The remaining tenure, or a fresh term',
   what:'A balance transfer moves your outstanding home loan to a new lender at a lower rate. The new lender repays your existing loan and you continue with them. It only makes sense if the interest saved exceeds the full cost of switching.',
   suitedTo:['Borrowers whose rate has drifted above current market rates','People with a good repayment record on the existing loan','Borrowers with substantial tenure remaining'],
   uses:['Reducing the interest rate on an existing home loan','Lengthening or shortening the remaining tenure','Combining a transfer with a top-up'],
   eligibility:['Existing home loan with a clean repayment record','Property title and documents in order','Income sufficient for the new lender’s assessment','Sufficient remaining tenure for the saving to be worthwhile'],
   docs:['Existing loan account statement and sanction letter','Outstanding balance and foreclosure letter from the current lender','Property documents held by the existing lender','KYC, income proof and bank statements'],
   fees:[['Processing fee','Charged by the new lender on the transferred amount.'],['Legal and technical','The new lender re-verifies the property, at actuals.'],['Foreclosure charge on the old loan','Nil for individuals on floating-rate home loans, by RBI rule.'],['Stamp duty on fresh mortgage','Per state schedule.']],
   repayment:stdRepay,
   advantages:['Can meaningfully reduce total interest over a long remaining tenure','An opportunity to renegotiate terms and service','A top-up can often be taken at the same time'],
   considerations:['Switching has real costs — processing, legal and stamp duty','A transfer late in the tenure saves little, since most interest is paid early','Resetting to a longer tenure can raise total interest even at a lower rate'],
   faqs:[['How do I know a transfer is worth it?','Compare the total remaining interest on your current loan against the total on the new one, then add the switching costs. Proceed only if you are genuinely ahead. Use the prepayment and EMI calculators to model it.'],['Will my current lender match the rate?','They may, if asked. It is usually worth requesting a rate review before going through a full transfer.'],...commonFaqs]},

  {id:'home-topup',family:'home',name:'Home Loan Top-up',icon:'Plus',
   description:'Additional borrowing on top of an existing home loan.',
   rate:null,max:'Subject to the property value and existing loan',tenure:'Usually aligned to the home loan',
   what:'A top-up is extra borrowing on a home loan you already hold, using the same property as security. Because the mortgage already exists, it is usually quicker and cheaper than a fresh personal loan, though more expensive than the home loan itself.',
   suitedTo:['Existing home loan borrowers with a clean record','People needing funds for renovation or other large costs','Borrowers who would otherwise take unsecured credit'],
   uses:['Home renovation or extension','Education or medical costs','Consolidating costlier debt','Business needs, subject to lender policy'],
   eligibility:['An existing home loan, usually with a minimum repayment track record','Property value comfortably above the combined borrowing','Income sufficient to service both loans'],
   docs:['Existing loan statement and repayment record','Updated income proof and bank statements','Property documents already held by the lender','KYC'],
   fees:[['Processing fee','Charged on the top-up amount.'],['Valuation','A fresh valuation may be required, at actuals.'],['Prepayment','As set out in the top-up sanction letter.'],['Documentation','At actuals.']],
   repayment:'Repaid alongside the home loan, either as a separate EMI or merged into a revised instalment. Confirm which structure applies.',
   advantages:['Cheaper than unsecured borrowing because the property is already security','Faster than arranging a new secured loan','Tenure can align with the existing home loan'],
   considerations:['It increases the debt secured against your home','Tax treatment depends on how the money is used — take advice','A longer tenure on a top-up can cost more in total than a shorter unsecured loan'],
   faqs:[['Is a top-up eligible for home loan tax benefits?','Only if the money is used for purposes the law recognises, such as construction or renovation of the property. Using it for other purposes generally does not qualify. Confirm with a tax adviser.'],...commonFaqs]},

  {id:'open-plot',family:'home',name:'Plot Loan',icon:'MapPinned',
   description:'Finance a plot for your future plans.',
   rate:null,max:'A share of the plot value',tenure:'5–20 years',
   what:'A loan to buy a residential plot, secured against the land. Plot loans usually carry shorter tenures than home loans, and some lenders require construction to begin within an agreed period.',
   suitedTo:['Buyers purchasing land to build on later','People buying in approved residential layouts','Investors in residential land, subject to lender policy'],
   uses:['Buying a residential plot','Purchasing in an approved layout','Securing land ahead of construction'],
   eligibility:['Plot within municipal limits or an approved layout','Clear, marketable title','Documented income to service the EMI','Willingness to begin construction within the lender’s timeframe, where required'],
   docs:['Title deed and ownership chain','Layout approval and land-use documents','Encumbrance certificate','KYC, income proof and bank statements'],
   fees:[['Processing fee','A percentage of the sanctioned amount.'],['Legal and technical','At actuals.'],['Prepayment','As set out in the sanction letter.'],['Stamp duty','Per state schedule.']],
   repayment:stdRepay,
   advantages:['Secures land now for construction later','Can often be converted to a composite construction loan','Longer tenure than unsecured borrowing'],
   considerations:['Tenures are shorter and LTV lower than for a built home','Tax deductions generally do not apply until construction is complete','Some lenders require construction to start within a fixed period'],
   faqs:[['Do home loan tax benefits apply to a plot loan?','Generally not on their own. Deductions typically become available once a house is constructed on the plot and the loan converts accordingly. Take tax advice.'],...commonFaqs]},

  /* ================= GOLD ================= */
  {id:'gold',family:'gold',name:'Gold Loan',icon:'Gem',
   description:'Turn eligible gold into quick liquidity.',
   rate:'8.05%',max:'A share of the assessed gold value',tenure:'3–36 months',
   what:'A gold loan is secured against gold jewellery you pledge with the lender. The gold is assayed for purity and weight, valued, and a proportion of that value is advanced. Because the security is held by the lender, income proof and credit score matter far less than for other borrowing.',
   suitedTo:['Households holding idle gold jewellery','Borrowers with no income proof or thin credit history','Anyone needing money quickly for a short period'],
   uses:['Short-term cash needs','Business working capital','Medical or education costs','Bridging a temporary shortfall'],
   eligibility:['Any adult owning eligible gold jewellery','No income proof or credit score required by most lenders','Gold of acceptable purity, typically 18–24 carat','Ornaments only — bars and coins are usually restricted'],
   docs:['PAN or Aadhaar for KYC','Address proof','The gold being pledged, for on-site assay'],
   fees:[['Processing fee','Often a small flat amount, set by the lender.'],['Valuation charge','For assaying and valuing the ornaments.'],['Prepayment','Frequently nil after a short initial period — confirm with the lender.'],['Storage','Ornaments are held in an insured vault, usually at no extra cost.']],
   repayment:'Several structures exist — regular EMIs, interest-only during the term with principal at maturity, or a single bullet repayment. Confirm which applies before you sign.',
   advantages:['Fastest disbursal of any secured loan, often the same day','No income proof or credit score needed in most cases','Rates well below unsecured borrowing','Short tenures keep total interest low'],
   considerations:['If you do not repay, the lender can auction your gold after due notice','Loan-to-value is capped by regulation, so you cannot borrow the full value','A fall in gold prices can trigger a margin call requiring you to pay down or pledge more','Sentimental jewellery is at genuine risk — borrow only what you can repay'],
   faqs:[['What happens if I cannot repay?','The lender must give you notice and follow the process set out in your agreement, after which it can auction the pledged gold to recover its dues. Any surplus after recovery is returned to you.'],['Is my gold safe?','Regulated lenders store pledged ornaments in insured vaults and return the same articles on repayment. Ask about storage and insurance arrangements before pledging.'],['Can I pledge coins or bars?','Most lenders accept ornaments only, and where coins are accepted there are usually weight and purity limits.'],...commonFaqs]},

  {id:'instant-gold',family:'gold',name:'Instant Gold Loan',icon:'Zap',
   description:'Same-day funds against pledged jewellery.',
   rate:null,max:'A share of the assessed gold value',tenure:'3–24 months',
   what:'The same secured product delivered on an expedited timeline. Because valuation happens in front of you and the security is taken immediately, disbursal can follow within the same visit at many lenders.',
   suitedTo:['Borrowers with an urgent, short-term need','People who can visit a branch with their ornaments','Anyone without documentation for other credit'],
   uses:['Emergency medical costs','Urgent business payments','Immediate short-term shortfalls'],
   eligibility:['Adult owning eligible gold ornaments','Valid KYC documents','Gold of acceptable purity'],
   docs:['PAN or Aadhaar','Address proof','The ornaments to be pledged'],
   fees:[['Processing fee','Small flat charge, set by the lender.'],['Valuation','For assay and valuation.'],['Prepayment','Often nil after a short initial period.'],['Storage','Insured vault storage, usually included.']],
   repayment:'As agreed at sanction — EMI, interest-only with bullet principal, or full bullet repayment.',
   advantages:['Among the fastest ways to raise secured funds','Minimal documentation','No credit score dependency in most cases'],
   considerations:['Speed can encourage borrowing more than needed','The auction risk is identical to any gold loan','Compare the rate against a standard gold loan — speed is sometimes priced in'],
   faqs:[['How quickly can funds arrive?','Many lenders disburse within the same visit once valuation and KYC are complete. No lender guarantees a specific time.'],...commonFaqs]},

  {id:'gold-jewellery',family:'gold',name:'Gold Loan Against Jewellery',icon:'Gem',
   description:'Borrow against household ornaments without selling them.',
   rate:null,max:'A share of the assessed value',tenure:'3–36 months',
   what:'Borrowing secured specifically on jewellery rather than coins or bullion. The lender assesses net gold weight, excluding stones and non-gold components, which is why the eligible amount is often lower than owners expect.',
   suitedTo:['Families with inherited or unused ornaments','Borrowers who want to retain ownership of the jewellery','People needing funds without selling assets'],
   uses:['Education fees','Wedding costs','Business working capital','Medical expenses'],
   eligibility:['Ownership of the ornaments being pledged','Valid KYC','Gold within the lender’s accepted purity range'],
   docs:['PAN or Aadhaar','Address proof','The ornaments, for assay'],
   fees:[['Processing fee','Set by the lender.'],['Valuation','For assay and net weight assessment.'],['Prepayment','Usually nil after an initial period.'],['Storage','Insured vault storage.']],
   repayment:'EMI, interest-only, or bullet repayment as agreed at sanction.',
   advantages:['Retain ownership rather than selling family jewellery','Lower rates than unsecured borrowing','Quick and light on documentation'],
   considerations:['Only the net gold content counts — stones and settings are excluded from valuation','Non-repayment leads to auction of the ornaments','Repeated rollovers can cost more than the jewellery is worth to you'],
   faqs:[['Do stones in my jewellery count towards the loan?','No. Lenders value net gold content by weight and purity. Stones, enamel and other materials are excluded.'],...commonFaqs]},

  /* ================= SECURITIES ================= */
  {id:'las',family:'securities',name:'Loan Against Securities',icon:'LineChart',
   description:'Raise funds against investments without selling them.',
   rate:null,max:'A share of approved holding value',tenure:'Usually renewable annually',
   what:'A loan secured by pledging financial assets — shares, mutual funds, bonds or deposits. You keep ownership and continue to receive dividends or growth, while the lender holds a lien. It is typically structured as an overdraft, so interest applies only to what you draw.',
   suitedTo:['Investors needing liquidity without exiting positions','People avoiding capital gains tax from a forced sale','Borrowers wanting a standby facility rather than a lump sum'],
   uses:['Short-term liquidity','Business working capital','Bridging a funding gap','Emergency expenses'],
   eligibility:['Ownership of securities on the lender’s approved list','Holdings in demat form, where required','Minimum portfolio value as set by the lender','Valid KYC and, usually, an existing account relationship'],
   docs:['PAN and Aadhaar','Demat account statement or holding statement','Pledge request through the depository','Bank account details'],
   fees:[['Processing fee','Charged at sanction and often at annual renewal.'],['Interest','Applied only to the amount drawn, not the full limit.'],['Pledge and depository charges','Levied by the depository for creating and releasing the pledge.'],['Renewal fee','Payable when the facility is renewed.']],
   repayment:'Interest is serviced monthly on the drawn balance. Principal is repaid on demand or at the end of the facility period, and the limit is reviewed periodically.',
   advantages:['Investments stay invested and continue to earn','Avoids crystallising capital gains through a sale','Interest only on the amount actually used','Usually quick to set up against approved securities'],
   considerations:['A market fall can trigger a margin call requiring cash or more collateral','If unmet, the lender can sell the pledged securities — possibly at a poor time','Only approved securities qualify, and haircuts vary widely by asset','Borrowing to invest further amplifies both gains and losses'],
   faqs:[['What is a margin call?','If the value of your pledged securities falls below the level the lender requires, they will ask you to repay part of the loan or pledge more. If you cannot, they may sell the securities.'],['Do I still receive dividends?','Generally yes — you remain the owner. Confirm the specific terms with your lender.'],...commonFaqs]},

  {id:'las-mutual-funds',family:'securities',name:'Loan Against Mutual Funds',icon:'PiggyBank',
   description:'Borrow against mutual fund units without redeeming them.',
   rate:null,max:'A share of approved unit value',tenure:'Usually renewable annually',
   what:'A facility secured by pledging mutual fund units. The lender marks a lien with the registrar or depository, and advances a proportion of value — typically more against debt funds than equity funds, because debt funds fluctuate less.',
   suitedTo:['Investors with meaningful mutual fund holdings','People avoiding exit loads or capital gains from redemption','Borrowers wanting a flexible standby limit'],
   uses:['Short-term liquidity','Emergency expenses','Business cash-flow gaps'],
   eligibility:['Units in schemes on the lender’s approved list','Holdings in the borrower’s own name','Minimum portfolio value as set by the lender'],
   docs:['PAN and Aadhaar','Mutual fund statement of account','Lien marking request to the registrar or depository','Bank details'],
   fees:[['Processing fee','At sanction and renewal.'],['Interest','On the drawn amount only.'],['Lien marking charges','Levied by the registrar or depository.'],['Renewal fee','On annual renewal.']],
   repayment:'Interest serviced monthly on the drawn balance; principal on demand or at facility end. Units are released once dues are cleared.',
   advantages:['Your SIPs and compounding continue uninterrupted','No exit load or capital gains crystallised','Higher advance rates against debt funds than equity'],
   considerations:['Equity funds attract larger haircuts because they are more volatile','A market fall can trigger a margin call','Pledged units cannot be redeemed or switched until the lien is released'],
   faqs:[['Can I continue my SIP while units are pledged?','Yes, ongoing SIPs generally continue. Only the specific units under lien are restricted.'],['Which funds qualify?','Each lender publishes an approved list with its own advance rates. Debt funds usually qualify for a higher proportion than equity funds.'],...commonFaqs]},

  {id:'las-shares',family:'securities',name:'Loan Against Shares',icon:'CandlestickChart',
   description:'Borrow against listed equity holdings.',
   rate:null,max:'A share of approved equity value',tenure:'Usually renewable annually',
   what:'A facility secured by pledging listed shares held in demat form. Advance rates are conservative because equity prices move sharply, and regulation caps how much may be lent against shares.',
   suitedTo:['Investors with concentrated listed holdings','Borrowers who expect their shares to recover or grow','People needing liquidity without exiting positions'],
   uses:['Short-term liquidity','Business needs','Bridging a funding gap'],
   eligibility:['Shares on the lender’s approved list, in demat form','Holdings in the borrower’s own name','Minimum portfolio value as set by the lender'],
   docs:['PAN and Aadhaar','Demat holding statement','Pledge instruction through the depository','Bank details'],
   fees:[['Processing fee','At sanction and renewal.'],['Interest','On the drawn amount only.'],['Depository pledge charges','For creating and releasing the pledge.'],['Renewal fee','On annual renewal.']],
   repayment:'Interest monthly on the drawn balance; principal on demand or at the end of the facility.',
   advantages:['Retain ownership, dividends and any upside','No capital gains triggered by a sale','Interest only on what you draw'],
   considerations:['Equity is volatile — margin calls are a real and frequent risk','Advance rates are conservative and regulated','Concentrated single-stock holdings may attract steeper haircuts','Borrowing to buy more shares magnifies losses as well as gains'],
   faqs:[['What happens in a market crash?','A sharp fall can breach the required margin. The lender will ask you to repay or pledge more, and may sell the shares if you cannot — often at depressed prices.'],...commonFaqs]},

  {id:'las-fd',family:'securities',name:'Loan Against Fixed Deposit',icon:'Landmark',
   description:'Borrow against a deposit without breaking it.',
   rate:null,max:'A high share of the deposit value',tenure:'Up to the deposit’s remaining term',
   what:'An overdraft or loan secured by your own fixed deposit. Because the security is a cash deposit with the same bank, it is the simplest secured borrowing available — the rate is usually a small margin above the deposit rate itself.',
   suitedTo:['Depositors needing short-term funds','Savers who would otherwise break a deposit and lose interest','Borrowers wanting the lowest-cost secured option'],
   uses:['Short-term cash needs','Emergency expenses','Bridging a temporary gap'],
   eligibility:['An existing fixed deposit with the lender','Deposit in the borrower’s name','Deposit not already pledged elsewhere'],
   docs:['Fixed deposit receipt or account details','KYC already held by the bank','Signed lien request'],
   fees:[['Processing fee','Often nil or nominal.'],['Interest','Typically a small margin above the deposit rate, on the drawn amount.'],['Prepayment','Usually nil.'],['Lien charges','Generally not applicable.']],
   repayment:'Interest serviced periodically; principal repaid on demand or adjusted against the deposit at maturity.',
   advantages:['Usually the cheapest secured borrowing available','The deposit continues to earn interest','Minimal documentation, since the bank already holds your KYC','No credit assessment in most cases'],
   considerations:['You cannot withdraw the deposit while the lien stands','The advance is a proportion of the deposit, not the whole amount','If unpaid, the bank simply adjusts the deposit against the dues'],
   faqs:[['Is this better than breaking the deposit?','Often yes, for short-term needs. Breaking a deposit usually means a penalty and lost interest. Compare the borrowing cost against what you would forfeit.'],...commonFaqs]},

  /* ================= EDUCATION ================= */
  {id:'education',family:'education',name:'Education Loan',icon:'GraduationCap',
   description:'Invest in your education and future.',
   rate:'7.00%',max:'Varies with course and collateral',tenure:'1–15 years',
   what:'An education loan funds tuition, living costs and related expenses for higher study in India or abroad. Lenders assess the institution and course alongside the co-applicant’s income, and repayment usually begins after a moratorium covering the course period.',
   suitedTo:['Students with confirmed admission to a recognised institution','Families with a resident co-applicant who has steady income','Students pursuing courses with clear employment outcomes'],
   uses:['Tuition and university fees','Living costs and accommodation','Travel for study abroad','Books, equipment and insurance'],
   eligibility:['Confirmed admission to a recognised institution','Indian resident co-applicant with documented income','Collateral usually required above a threshold amount','No significant academic gap, as assessed by the lender'],
   docs:['Admission letter and fee structure','Academic mark sheets from class X onward','Co-applicant income proof and bank statements','Collateral documents where the loan exceeds the unsecured threshold','Passport and visa for overseas study'],
   fees:[['Processing fee','Often nil or low for domestic courses; overseas loans may attract a charge.'],['Moratorium','Course duration plus a grace period, commonly six to twelve months.'],['Prepayment','Generally nil across lenders.'],['Insurance','Some lenders require credit life cover on larger loans.']],
   repayment:'Repayment usually begins after the moratorium — the course period plus a grace period. Interest may accrue during the moratorium; servicing it while studying reduces the total considerably.',
   advantages:['Interest paid is deductible under Section 80E, with no upper limit','Moratorium means repayment starts after study','Longer tenures keep instalments manageable','Builds the student’s own credit history'],
   considerations:['Interest accruing during the moratorium is added to the debt if not serviced','Loans above a threshold need collateral, often family property','The co-applicant is fully liable if the student cannot repay','Currency movements affect the real cost of overseas study'],
   faqs:[['When does repayment start?','After the moratorium, which typically covers the course period plus six to twelve months. Some lenders expect interest to be serviced during study.'],['Is a co-applicant compulsory?','Almost always, for both domestic and overseas loans. The co-applicant is jointly liable for the debt.'],['What tax benefit applies?','Section 80E allows a deduction for the full interest paid, with no upper limit, for up to eight years from when repayment begins. Principal is not deductible.'],...commonFaqs]},
];
